version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - mongodb
    env_file:
      - .env
    networks:
      - app-network

  redis:
    container_name: redis6
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - app-network
    volumes:
      - redis_data:/data

  mongodb:
    container_name: mongodb6
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    networks:
      - app-network
    volumes:
      - mongo_data:/data/db

networks:
  app-network:

volumes:
  redis_data:
  mongo_data:
